#server基本配置
server:
  servlet:
    context-path: /

#指定特定环境的变量配置
spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
    timeout: 3000
    port: 6379
    password: P@sswd
    database: 0 #初始化16个库(0~15，默认使用0)
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制)
        min-idle: 0 # 连接池中的最小空闲连接

server:
  tomcat:
    uri-encoding: utf-8
  port: 8081
